//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class contribuinte
    {
        public contribuinte()
        {
            this.factura_contribuinte = new HashSet<factura_contribuinte>();
        }
    
        public decimal id { get; set; }
        public string nome { get; set; }
        public string morada { get; set; }
    
        public virtual ICollection<factura_contribuinte> factura_contribuinte { get; set; }
    }
}
