//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolucao
    {
        public decimal quantidade { get; set; }
        public decimal item_numero { get; set; }
        public string factura_codigo { get; set; }
        public string nota_credito_codigo { get; set; }
    
        public virtual item item { get; set; }
        public virtual nota_credito nota_credito { get; set; }
    }
}
