//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public factura()
        {
            this.change_log = new HashSet<change_log>();
            this.items = new HashSet<item>();
            this.nota_credito = new HashSet<nota_credito>();
        }
    
        public string codigo { get; set; }
        public decimal estado { get; set; }
        public System.DateTime data_criacao { get; set; }
        public Nullable<System.DateTime> data_complecao { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<decimal> iva { get; set; }
    
        public virtual ICollection<change_log> change_log { get; set; }
        public virtual factura_contribuinte factura_contribuinte { get; set; }
        public virtual ICollection<item> items { get; set; }
        public virtual ICollection<nota_credito> nota_credito { get; set; }
    }
}
