//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_contribuinte
    {
        public string factura_codigo { get; set; }
        public Nullable<decimal> contribuinte_id { get; set; }
    
        public virtual contribuinte contribuinte { get; set; }
        public virtual factura factura { get; set; }
    }
}
