//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_credito
    {
        public nota_credito()
        {
            this.devolucaos = new HashSet<devolucao>();
        }
    
        public string codigo { get; set; }
        public decimal estado { get; set; }
        public System.DateTime data_criacao { get; set; }
        public Nullable<System.DateTime> data_complecao { get; set; }
        public string factura_codigo { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<decimal> iva { get; set; }
    
        public virtual ICollection<devolucao> devolucaos { get; set; }
        public virtual factura factura { get; set; }
    }
}
